// Code generated by QIX generator (./schema/generate.go) for Qlik Associative Engine version 12.401.0 . DO NOT EDIT.
package enigma

const (
	Version = "0.1.0"
	// QixVersion is the Qix API version enigma was generated for.
	QixVersion = "12.401.0"
)
