name: release-enigma-go
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Release Version (major, minor, patch)
        required: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '^1.17'
      - name: Checkout enigma-go repo
        uses: actions/checkout@v2  
        with:
          repository: qlik-oss/enigma-go
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN}}
      - name: Setup Git environment
        run: |
          git config --global user.email "no-reply@example.com"
          git config --global user.name "github-actions-bot"
      - name: Create enigma-go release
        run: |                  
          ./release/release.sh ${{ github.event.inputs.version }}
          git push --follow-tags
